/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author ayrto
 */
public class Menú extends javax.swing.JFrame {

    /**
     * Creates new form Menú
     */
    public Menú() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_NvoJugador = new javax.swing.JButton();
        Btn_NvoEntrenador = new javax.swing.JButton();
        Nvo_Masajista = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Btn_ListaEquipo = new javax.swing.JButton();
        Btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btn_NvoJugador.setText("Jugador");
        Btn_NvoJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NvoJugadorActionPerformed(evt);
            }
        });

        Btn_NvoEntrenador.setText("Entrenador");
        Btn_NvoEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NvoEntrenadorActionPerformed(evt);
            }
        });

        Nvo_Masajista.setText("Masajista");
        Nvo_Masajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nvo_MasajistaActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FUTBOL CLUB BARCELONA");

        Btn_ListaEquipo.setText("Mostrar Lista de Equipo");
        Btn_ListaEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ListaEquipoActionPerformed(evt);
            }
        });

        Btn_Salir.setText("Salir");
        Btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_ListaEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_NvoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_NvoEntrenador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nvo_Masajista))
                    .addComponent(Btn_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Btn_NvoJugador)
                    .addComponent(Btn_NvoEntrenador)
                    .addComponent(Nvo_Masajista))
                .addGap(55, 55, 55)
                .addComponent(Btn_ListaEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ListaEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ListaEquipoActionPerformed
        ListadeEquipo abrirLista= new ListadeEquipo();
        abrirLista.setVisible(true);
        abrirLista.pack();
        this.dispose();
    }//GEN-LAST:event_Btn_ListaEquipoActionPerformed

    private void Btn_NvoJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NvoJugadorActionPerformed
        NuevoJugador agregarJugador= new NuevoJugador();
        agregarJugador.setVisible(true); //hace la ventana visible
        agregarJugador.pack();
        this.dispose();
    }//GEN-LAST:event_Btn_NvoJugadorActionPerformed

    private void Btn_NvoEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NvoEntrenadorActionPerformed
        NuevoEntrenador agregarEntrenador= new NuevoEntrenador();
        agregarEntrenador.setVisible(true); //hace la ventana visible
        agregarEntrenador.pack();
        this.dispose();
    }//GEN-LAST:event_Btn_NvoEntrenadorActionPerformed

    private void Nvo_MasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nvo_MasajistaActionPerformed
        NuevoMasajista agregarMasajista= new NuevoMasajista();
        agregarMasajista.setVisible(true); //hace la ventana visible
        agregarMasajista.pack();
        this.dispose();
    }//GEN-LAST:event_Nvo_MasajistaActionPerformed

    private void Btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalirActionPerformed
        System.exit(0);   
    }//GEN-LAST:event_Btn_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menú().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_ListaEquipo;
    private javax.swing.JButton Btn_NvoEntrenador;
    private javax.swing.JButton Btn_NvoJugador;
    private javax.swing.JButton Btn_Salir;
    private javax.swing.JButton Nvo_Masajista;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
